name: rolify
description: The perfect app for your roleplay sessions! Play sounds in background simultaneously without using your internet connection.

version: 3.1.1+25

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  audio_service: ^0.18.15
  audio_session: ^0.1.21
  equatable: ^2.0.5
  event_bus: ^2.0.0

  flutter_bloc: ^8.1.6
  flutter_neumorphic_plus: 3.3.0

  flutter_svg: ^1.1.6
  just_audio: ^0.9.40
  path_provider: ^2.1.4
  shared_preferences: ^2.3.2
  sqflite: ^2.4.1
  url_launcher: ^6.3.1

  cupertino_icons: ^1.0.8




dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_launcher_icons_maker: ^0.10.2
  flutter_test:
    sdk: flutter

flutter_icons:
  android: 'launcher_icon'
  ios: true
  macos: true
  windows: true
  image_path: 'assets/launcher_icon/512px_512px.png'
  adaptive_icon_background: 'assets/launcher_icon/background.png'
  adaptive_icon_foreground: 'assets/launcher_icon/ic_launcher_foreground.png'

flutter:
  uses-material-design: true
  assets:
    - assets/audios/
    - assets/images/
    - assets/launcher_icon/
    - assets/icons/
  fonts:
    - family: AssetAudioPlayer
      fonts:
        - asset: fonts/AssetAudioPlayer.ttf
    - family: Inter-Regular.ttf
      fonts:
        - asset: fonts/Inter-Regular.ttf
