
allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}

subprojects {
    def injectNamespace = { project ->
        if (project.hasProperty('android') && project.android.namespace == null) {
            def manifestFile = project.file("src/main/AndroidManifest.xml")
            if (manifestFile.exists()) {
                def manifestContent = manifestFile.getText()
                def matcher = manifestContent =~ /package="([^"]+)"/
                if (matcher.find()) {
                    project.android.namespace = matcher.group(1)
                } else {
                    project.android.namespace = project.group
                }
            } else {
                project.android.namespace = project.group
            }
        }
    }
    if (project.state.executed) {
        injectNamespace(project)
    } else {
        project.afterEvaluate {
            injectNamespace(project)
        }
    }
}
